### ISSUE TITLE
App is functional for users with visual impairments and works with a11y settings

### ISSUE THREAD

**Issue by OwenLaRosa** [SwiftFest/ios-app#42] opened 2018-06-03 00:58 UTC
@SeanROlszewski @ZevEisenberg Following up from our discussion at Learn Swift Boston, I'm interested in helping make sure the app meets accessibility standards. This story is to track bugs and implement features related to built-in accessibility settings, particularly Dynamic Type and VoiceOver.

**Comment by SeanROlszewski** [comment] 2018-06-03 01:08
@OwenLaRosa we would love that. Thanks for taking the initiative to add this story to the backlog!

Would you mind doing an initial audit to determine what still needs to be done in regards to Dynamic Type and VoiceOver? We put a little effort into adding support for Dynamic Type, though I would be willing to bet there are parts of the app where it isn't supported. So far, no one has gone through the app and tried to see what the experience is like using VoiceOver.

**Comment by OwenLaRosa** [comment] 2018-06-03 03:11
I've been doing some testing with Dynamic Type and VoiceOver enabled. Here is what I found.

Dynamic Type:

1. The segmented control’s height is calculated once, based on the font size at launch time. If you launch the app with an accessibility font enabled, the height of the segmented control expands, but the text does not change size. The height does not change when switching font sizes if the app was already running, however. As the segment correctly displays a context menu on long press, the control and its inner text should not change size based on the system font.
2. If a day is selected by long pressing the segmented control (and changing the day with the context menu) the previously selected day’s label blends in with the control’s background.
3. The section header’s text overflows the available height. 
4. In the Agenda table view cells, the speaker’s image should be moved above the text in the cell or hidden altogether when one of the accessibility fonts is used. This is not a “must”, but follows Apple’s recommendations to limit displayed content when larger fonts are used. The image eats up a disproportionate amount of horizontal space.
5. The time text field on the Agenda table view cell is truncated. Based on the prior point, I’m wondering if this text is necessary other than for aesthetic reasons, since the time is already displayed in the table header. Currently, all talks appear to be labeled for one hour, including “Choosing the Right Design Pattern (1.5h)”. Fixing this would explain the time range displayed on each cell.
6. The names shown on the Speakers and Team tabs are truncated, and the cell height does not expand.
7. Scrollable text on the detail view (from the Speakers tab) does not resize.

VoiceOver:

I’ll admit I’m not a proficient VoiceOver user so there could be more "nice to haves". But I did encounter a few annoyances. The app is otherwise fully navigable.

1. The time abbreviations in the titles are read as “one point five H”
2. Times on the Agenda screen are read “3PM 4PM” without “to”.
3. Detail page’s “back button” says “back button icon”
4. Sponsor names (accompanying the logos) are invisible to VoiceOver

Additionally, as I was using VoiceOver on an iPad, I noticed the following layout issues:

1. Speaker photos on the Agenda screen are slightly offscreen in both vertical directions. The image views on other screens have appropriate margin.
2. The gradient on the detail page only takes up half the screen.

**Comment by SeanROlszewski** [comment] 2018-06-08 04:01
@OwenLaRosa this is awesome, thank you for putting this together. we were crunching on an initial build to get past apple in time for the conference, but over the next week and a half we're prioritizing this set of improvements alongside #11 

to that end, some changes were made to the app that I believe addressed a few of your issues, but by no means is it all-encompassing. if you wanted to tackle a few of these items, that would be enormously helpful. We're happy to pair with you to get you ramped up on the code, or otherwise help you get familiar with the codebase.

**Comment by OwenLaRosa** [comment] 2018-06-09 02:19
@SeanROlszewski Yes, I would love to help implement these. I should be able to dedicate some time this weekend to address most of the high priority items that remain here. Looking forward to be able to contribute.

**Comment by mdiasdev** [comment] 2019-07-14 00:30
## Dynamic Type:

1. The segmented control’s height is calculated once
   - **_This seems to be by design by Apple. I read about a couple solutions, but they seemed very hackie; so I opted not to implement it_**
2. If a day is selected by long pressing the segmented control the previously selected day’s label blends in with the control’s background.
   - _**cannot reproduce**_
3. The section header’s text overflows the available height. 
   - **_Should be fixed_**
4. In the Agenda table view cells, the speaker’s image should be moved above the text
   - _**won't do for this release. created issue #65 for future tracking**_
5. The time text field on the Agenda table view cell is truncated.
   - _**it looks like this was not included this year**_
6. The names shown on the Speakers and Team tabs are truncated, and the cell height does not expand.
   - _**fixed**_
7. Scrollable text on the detail view (from the Speakers tab) does not resize.
  - _**fixed**_

## VoiceOver:
1. The time abbreviations in the titles are read as “one point five H”
   - _**appears to be omitted this year**_
2. Times on the Agenda screen are read “3PM 4PM” without “to”.
   - _**appears to be omitted this year**_
3. Detail page’s “back button” says “back button icon”
   - _**cannot reproduce**_
4. Sponsor names (accompanying the logos) are invisible to VoiceOver
   - _**will retest after @GhostScientist completes #54**_

## layout issues:
1. Speaker photos on the Agenda screen are slightly offscreen in both vertical directions.
   - **_Tried on several iPad simulators and could not reproduce this_**
2. The gradient on the detail page only takes up half the screen.
   - _**this is by design, it covers the "header"**_

**Comment by mdiasdev** [comment] 2019-07-20 17:10
Resolved in PR #66

**Closed by mdiasdev** 2019-07-20 17:10 UTC
